### ISSUE TITLE
Guzzle 5 mock not working

### ISSUE THREAD

**Issue by jenssegers** [jenssegers/php-proxy#22]
I can't get the Guzzle 5 mock stuff to work correctly. @omares, have you worked with Guzzle 5 yet?

**Comment by omares** [comment]
nope but ill take a look if you want :)

**Comment by jenssegers** [comment]
That would be great, I've been scratching my head for a couple of hours :p

**Comment by omares** [comment]
Ok give me some time please, i am rather busy right now.
