### ISSUE TITLE
RequestFilter not adding into Request

### ISSUE THREAD

**Issue by bagwaa** [jenssegers/php-proxy#25]
When I create a custom request filter implementing the `RequestFilterInterface` then I am seeing some mixed results.

If I use the following filter to manipulate / add a new header, then this works fine.

``` php
<?php

namespace Proxy\Filters;

use Proxy\Request\Filter\RequestFilterInterface;
use Symfony\Component\HttpFoundation\Request;

class CustomRequestFilter implements RequestFilterInterface {

    public function filter(Request $request)
    {
        $request->headers->add(['foo' => 'bar']);
        return $request;
    }

}
```

However, if I do exactly the same but attempt to add content to the actual request, then the item is not added at all and is ignored.

``` php
<?php

namespace Proxy\Filters;

use Proxy\Request\Filter\RequestFilterInterface;
use Symfony\Component\HttpFoundation\Request;

class CustomRequestFilter implements RequestFilterInterface {

    public function filter(Request $request)
    {
        $request->request->add(['bar' => 'baz']);
        return $request;
    }

}
```

**Comment by bagwaa** [comment]
After some investigation.

`/src/Adapter/Guzzle/GuzzleAdapter.php`

the `convertRequest(Request $request)` method casts the Symfony request into a string, and then passes this on to the MessageFactory class, this casting seems to lose everything in the request property in the Symfony request.

Once this is confirmed as a bug and not just me `holding it wrong` which is entirely possible, I will make a PR over the next few days.

**Comment by jenssegers** [comment]
It looks like a bug, but I don't understand why it would lose the changes when casting to a string.

**Comment by jenssegers** [comment]
I did some tests, but for me it was working okay. I added an `Authorization` header to the request and it was passed to Guzzle.

I did some small changes to the filter system. You can now also pass anonymous functions as filters.

Let me know if the last version also fixed your problem.

**Comment by bagwaa** [comment]
Yeah passing in headers was always fine, it was just when passing in more items onto the request.

```php
$request->request->add(['bar' => 'baz']);
```

I can have a look later.  I did also see some weirdness with applyRequestFilter and assigning that back, I see you have fixed that, thanks :)

Rich

**Comment by jenssegers** [comment]
Is the original issue fixed as wel?

**Comment by bagwaa** [comment]
The original issue of trying to add items to the request (not the header, the actual request) still exists, I am a bit confused at the moment as to why a casting to a string loses information when it is listed perfectly fine pre-casting.

maybe I can put together some class to handle this conversion, either to string or directly to some JSON object, very strange one for sure.

```php
    /**
     * Convert the Symfony request to a Guzzle request.
     *
     * @param  Request $request
     * @return RequestInterface
     */
    protected function convertRequest(Request $request)
    {
        return $this->messageFactory->fromMessage((string) $request);
    }
```

**Comment by bagwaa** [comment]
Further investigation, I think this is down to how the Symfony Request object is handling the casting via the toString() method in Request, this method in turn calls getContent() which then references php://input to get the contents once, not 100% sure yet, but I have a feeling this is where things are going a bit wonky, will keep playing around.
