### ISSUE TITLE
Guzzle 6.0 was released

### ISSUE THREAD

**Issue by ctubio** [jenssegers/php-proxy#27]
just saying, [Guzzle 6.0](https://github.com/guzzle/guzzle/releases/tag/6.0.0) was recently released.

Maybee.. we can update the dependencies?

(congrats for php-proxy!)

**Comment by jenssegers** [comment]
I updated the current dev-master to use Guzzle 6, will soon tag new version.

**Comment by jenssegers** [comment]
Wondering when Symfony will release a PSR7 compliant version of their Request/Response objects.
