### ISSUE TITLE
How to edit response content with filter?

### ISSUE THREAD

**Issue by ghprod** [jenssegers/php-proxy#29]
Hi, 

i tried to make some filter response to change the content, but i'm always get non well-formed character like this

![image](https://cloud.githubusercontent.com/assets/1922652/10290040/ff155216-6bcb-11e5-9375-64e148d2d3c6.png)

And this is my code, i use `dump()` for debug purpose

```php
class ModifyContent implements ResponseFilterInterface
{
    public function filter(Response $response)
    {
        dump($response->getContent());

        // $crawler = HtmlPageCrawler::create($response->getContent());

        // $response->setContent($crawler);

        return $response;
    }
}
```

Any idea how can i able to parsing content with some crawler/selector, modify it, and setContent() back ?

Thanks

**Comment by jenssegers** [comment]
That is weird. Is `->getContent()` returning a stream? Maybe try `->getContent()->getBody()`.

**Comment by ghprod** [comment]
Hi @jenssegers 

finally figured out, i need to remove `accept-encoding` header from my browser/local request with request filter

```php
<?php

namespace App\Filters\Request;

use Proxy\Request\Filter\RequestFilterInterface;
use Symfony\Component\HttpFoundation\Request;

class RemoveAcceptEncoding implements RequestFilterInterface
{
    public function filter(Request $request)
    {
        $request->headers->remove('accept-encoding');

        return $request;
    }
}
```

Do u know why it happen?

Thanks

**Comment by jenssegers** [comment]
The server probably returned a gzipped response, but I thought the client would convert it. Might need to look into that.

**Comment by jenssegers** [comment]
I just did a major rewrite on master btw. I don't know how much time you have to try it out :)

**Comment by jenssegers** [comment]
In the new version this would look like this:

```
$proxy->filter(function($request, $response, $next) {
    $request = $request->removeHeader('Accept-Encoding');
    $response = $next($request, $response);
    return $response;
});
```

**Comment by ghprod** [comment]
`withoutHeader` method is came from PSR7 request right?

btw i'll try it :dancer: 

Thanks

**Comment by jenssegers** [comment]
Yup. The rewrite is complete PSR7 with middleware filters :)

**Comment by ghprod** [comment]
:+1: 

Great.. Thanks a lot @jenssegers 

:100:
