### ISSUE TITLE
 Call to undefined method Proxy\\Proxy::filter() 

### ISSUE THREAD

**Issue by Khalav** [jenssegers/php-proxy#36]
After downloading and installing via composer and using the first example on, I am getting this error:

```
Call to undefined method Proxy\\Proxy::filter() 
```

 on this line:

```
$proxy->filter(new RemoveEncodingFilter());
```

**Comment by josephros** [comment]
I had this issue (amongst some others) and found requiring the dev master via composer rather than the standard version which composer installs fixed it for me by pulling in more up to date code. Here's my composer.json:

```
{
    "require": {
        "jenssegers/proxy": "dev-master",
        "zendframework/zend-diactoros": "^1.3"
    },
    "minimum-stability": "dev"
}
```

**Comment by zacharee** [comment]
I tried the suggestion, but I still have the error.
