### ISSUE TITLE
Response emitter not working.

### ISSUE THREAD

**Issue by flip111** [jenssegers/php-proxy#42]
I try the dev-master branch (latest commit of the time of this posting). These are the last lines of my script:

```
// Forward the request and get the response.
$response = $proxy->forward($request)->to('http://server.com:80');
//echo (string) $response->getBody(); die();
// Output response to the browser.
(new Zend\Diactoros\Response\SapiEmitter)->emit($response);
```

Nothing appears from the response in the browser, if i uncomment the echo statement i can see the html rendered (website appears without css and images in this case).

**Comment by giggsey** [comment]
@flip111: I was having the same problem when I was using the built in PHP server on Windows (might have also happened on Linux too, didn't try it).

Once I switched to my usual nginx/php-fpm mix, it started working fine.

**Comment by flip111** [comment]
@giggsey yes as i remember i was using the built-in server. Since using another server is a workaround and not a fix i will leave this issue open.

**Comment by sebbuku** [comment]
For some reason I noticed the same problem in Laravel 5.3 on vagrant (nginx server). The headers were sent to the browser but the body of the response didn't.
`return $response->getBody();`
did the trick though.
