### ISSUE TITLE
problem with files upload

### ISSUE THREAD

**Issue by marek-l** [jenssegers/php-proxy#43]
Hi,

when I try to upload files, these are not available on the forwarded to site. Is there known any problem with this?

thanks
MarekL

**Comment by boynet** [comment]
any info about it? really looking for php proxy but cant find any docs about it :)

**Comment by marek-l** [comment]
I am using this code with success, proxy works ok:

```
use GuzzleHttp\Client;

use GuzzleHttp\Exception\ClientException;
use Proxy\Adapter\Guzzle\GuzzleAdapter;
use Proxy\Proxy;
use Symfony\Component\HttpFoundation\JsonResponse;
use Zend\Diactoros\ServerRequestFactory;

$client = new Client();
$originRequest = ServerRequestFactory::fromGlobals();
$proxy = new Proxy(new GuzzleAdapter($client));

... any logic to do with request

$response = $proxy
		->forward($originRequest)
		->to($url);
(new Zend\Diactoros\Response\SapiEmitter)->emit($response);
```

**Comment by stdclass** [comment]
What worked for me was to add:


use Laminas\Diactoros\ServerRequestFactory;

and create the request with:

$request = ServerRequestFactory::fromGlobals();


The request I got with Laravel DI / ServerRequestInterface lacked the uploaded files.

**Comment by stdclass** [comment]
@sinuraya nope, still does not work with the example code above (@marek-l).

At the request target, the $_FILES is always empty
