### ISSUE TITLE
Support http-foundation:^2.6|^3.0 for 2.2.2 point release?

### ISSUE THREAD

**Issue by andig** [jenssegers/php-proxy#48]
If you'd accept a PR I'd be happy to create one. As I'm not on PSR7 yet that would greatly simplify my testing dependencies.

**Comment by omar-elsherif** [comment]
What is a PR?

**Comment by andig** [comment]
> What is a PR?

A pull request? Didn't know what else to call it ;)

**Comment by jenssegers** [comment]
You can use the psr-http-message-bridge to convert Symfony requests: https://github.com/symfony/psr-http-message-bridge

**Comment by andig** [comment]
Wow, didn't know that- great! Any chance for tagging a stable 3.0 to use it with?

**Comment by KTP95** [comment]
Same question, My project has dependences for 
        "symfony/http-foundation": "^3.1"

When i try install via composer get error:

    - jenssegers/proxy v2.2.1 requires symfony/http-foundation ~2.6
	satisfiable by symfony/http-foundation[2.6.x-dev,.....................v2.8.9] 
	but these conflict with your requirements or minimum-stability.

Some solution for use composer and no-conflicts ?
