### ISSUE TITLE
Cannot get response code for some occasions

### ISSUE THREAD

**Issue by shalindasuresh** [jenssegers/php-proxy#49]
Is there any way to get status code before output the html as for response? I need to get status code before desplay html page.example I dont need to display unauthorized html page instead I need to filter response code and re-authorized.I  tried with response->getStatusCode().this works when there is success response but not for  any other http status code,Handling this kind of situation was easy with prior versions.

**Comment by dasun4u** [comment]
Use this For Guzzle 6 bro... ;)
$client = new \GuzzleHttp\Client(['http_errors' => false]);

**Comment by shalindasuresh** [comment]
Thanks @dasun4u  ,that's what I wanted (y)
