### ISSUE TITLE
Current demo code requires more libraries

### ISSUE THREAD

**Issue by halfer** [jenssegers/php-proxy#51]
The demo code for the current unstable version in the `README` does not work without an extra class library, `Zend\Diactoros\ServerRequestFactory`. Is it OK to send a PR to fix up the docs?

It just needs something like this in the appropriate place:

    composer require zendframework/zend-diactoros

**Comment by jenssegers** [comment]
The composer file has `"zendframework/zend-diactoros": "^1.0",` though.

**Comment by halfer** [comment]
Ah! I didn't spot that, thanks. I installed via Composer, and that gave me the current stable version, which does not include that.
