### ISSUE TITLE
Zend\Diactoros\Response\SapiEmitter has been depricated

### ISSUE THREAD

**Issue by joshualjohnson** [jenssegers/php-proxy#75]
Zend\HttpHandlerRunner\Emitter\SapiEmitter is the replacement for the deprecated class. As a part of updating this, you will need to remove the use of `"zendframework/zend-diactoros": "^1.0 || ^2.0",` and update it with `"zendframework/zend-httphandlerrunner": "^1.1"`

**Comment by jmolivas** [comment]
@jenssegers will you accept a PR with this changes updating the deprecated dependencies? I got a fork with this changes applied.

**Comment by jenssegers** [comment]
Sure thing!

**Comment by jmolivas** [comment]
@jenssegers  PR is here https://github.com/jenssegers/php-proxy/pull/78

CircleCI is complaining when PHP version < 7.1
https://travis-ci.org/jenssegers/php-proxy/jobs/659028737

![image](https://user-images.githubusercontent.com/366275/76060501-4c3a8e00-5f36-11ea-85eb-2e4399c004ee.png)

7.0 and even 7.1 are deprecated now, not sure if CircleCI should keep testing those deprecated versions, what do you think?
https://www.php.net/supported-versions.php

**Comment by jmolivas** [comment]
PR was merged this should be closed
