### ISSUE TITLE
PHP Proxy is converting the script URLs

### ISSUE THREAD

**Issue by optimizerpro** [jenssegers/php-proxy#9]
Hi,
I am using PHP proxy to get script of cross domain, But I am facing an issue. While I am calling the script of cross domain, it is also converting the link on page onto proxy page. I want the script proper but the links on scripts should be as it is. Can you please help me to sort out it.

I am giving you an example: I call a url, the whole script is coming on my end with images but some links are also converting as proxy like:  src="http://optimizerpro.com/proxy/index.php?q=aHR0cDovL3NvY2lhbGJhY2tncm91bmQubmV0L3lvL2Jhbm5lci5qcGc%3D">

This is generally something else(www.ngicorporation.com) but while I used proxy it converts according to my domain.

Can you please tell me the way so that it remain same? Is there possbility ?

I will be so thankfull for your suggestion.
## 

Yogendra Gupta
Project Manager, Mob: +919560194775,
247 Experts (P) Ltd | A-83, Okhla, New Delhi | New Delhi, India - 110019

**Comment by BrixSat** [comment]
Still not working?
